"""
DiscoveryOS - Dashboard Renderer.

This script reads the prioritized_matrix.json generated by discovery_engine.py
and produces a presentation-ready markdown file (DASHBOARD.md) containing
formatted tables, KPI callouts, and strategic briefs.
"""

import os
import json
import sys
import argparse
from datetime import datetime


def get_severity_badge(severity: int) -> str:
    """
    Returns a visual representation and label for numerical severity.
    """
    if severity >= 5:
        return "🔴 Critical (5)"
    elif severity == 4:
        return "🟠 High (4)"
    elif severity == 3:
        return "🟡 Medium (3)"
    elif severity == 2:
        return "🟢 Low (2)"
    else:
        return "⚪ Minor (1)"


def render_markdown(matrix_data: dict, output_path: str):
    """
    Formats the JSON matrix data into a presentation-ready markdown dashboard.
    """
    strategic_focus = matrix_data.get("strategic_focus", "No strategic brief generated.")
    items = matrix_data.get("items", [])
    
    # Calculate stats
    total_items = len(items)
    max_severity = max([item.get("severity", 0) for item in items]) if items else 0
    impacted_areas = sorted(list(set([item.get("feature_area", "Unknown") for item in items])))
    
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md = []
    md.append("# 🧠 DiscoveryOS Product Intelligence Dashboard")
    md.append(f"*Generated on: {now_str}*")
    md.append("\n---\n")

    # 1. KPI Summary Block
    md.append("## 📊 Executive Summary")
    md.append("| Metric | Value |")
    md.append("| :--- | :--- |")
    md.append(f"| **Total Feedback Items Parsed** | {total_items} |")
    md.append(f"| **Max Severity Encountered** | {get_severity_badge(max_severity)} |")
    md.append(f"| **Impacted Feature Areas** | {', '.join(impacted_areas)} |")
    md.append("\n")

    # 2. Strategic Focus Blockquote
    md.append("## 🎯 Strategic Focus Brief")
    md.append("> **AI PM Directional Brief:**")
    # Wrap lines of strategic focus for proper blockquote rendering
    for line in strategic_focus.strip().split("\n"):
        md.append(f"> {line}")
    md.append("\n---\n")

    # 3. Quantitative Prioritization Matrix Table
    md.append("## 📋 Quantitative Prioritization Matrix")
    md.append("The table below shows customer feedback categorized, prioritized by severity, and mapped to concrete product roadmap directives.")
    md.append("\n")
    md.append("| Feature Area | User Segment | Severity | Business Impact | Product Action / Roadmap Directive |")
    md.append("| :--- | :--- | :--- | :--- | :--- |")
    
    # Sort items by severity descending so the most critical items are at the top
    sorted_items = sorted(items, key=lambda x: x.get("severity", 0), reverse=True)
    
    for item in sorted_items:
        area = item.get("feature_area", "N/A")
        segment = item.get("user_segment", "N/A")
        sev = get_severity_badge(item.get("severity", 0))
        impact = item.get("business_impact", "N/A")
        action = item.get("product_action", "N/A")
        
        md.append(f"| **{area}** | {segment} | {sev} | {impact} | {action} |")
    
    md.append("\n---\n")
    md.append("## 💡 Product Team Guidance")
    md.append("- **Critical Severity (5):** Requires immediate hotfix or inclusion in the current sprint.")
    md.append("- **High Severity (4):** Prioritize in the upcoming sprint planning.")
    md.append("- **Medium/Low (1-3):** Queue in the product backlog for refinement.")

    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(md))


def main():
    parser = argparse.ArgumentParser(description="DiscoveryOS Dashboard Renderer")
    parser.add_argument(
        "--input", 
        default="prioritized_matrix.json", 
        help="Path to the prioritized matrix JSON file (default: prioritized_matrix.json)"
    )
    parser.add_argument(
        "--output", 
        default="DASHBOARD.md", 
        help="Path to save the output markdown file (default: DASHBOARD.md)"
    )
    args = parser.parse_args()

    # Resolve paths relative to this script's directory if they are relative
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_path = args.input if os.path.isabs(args.input) else os.path.join(script_dir, args.input)
    output_path = args.output if os.path.isabs(args.output) else os.path.join(script_dir, args.output)

    print("=== DiscoveryOS Dashboard Renderer ===")
    
    if not os.path.exists(input_path):
        print(f"Error: Prioritized matrix file not found: {input_path}", file=sys.stderr)
        print("Please run discovery_engine.py first to generate this file.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            matrix_data = json.load(f)
    except json.JSONDecodeError:
        print(f"Error: Failed to parse matrix file '{input_path}' as valid JSON.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading {input_path}: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        render_markdown(matrix_data, output_path)
        print(f"Success: Dashboard successfully written to {output_path}")
    except Exception as e:
        print(f"Error generating dashboard: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
